In [6]:
import pandas as pd
from pathlib import Path

In [11]:
data_path=Path("../data/raw/tracing-data/social-network")
csv_files=list(data_path.rglob("*.csv"))
len(csv_files)

32

In [ ]:
df=pd.read_csv(csv_files[0])

In [23]:
df.head()

,trace_id,1_nginx_compose-post,2_mediaservice_upload,6_composepost_uploadmedia,3_userservice_upload,7_composepost_uploadcreator,4_textservice_upload,8_urlservice_upload,9_usermentionservice_upload,10_composepost_uploadtext,...,22_redishashset_update_url,23_poststorage_storepost_user,24_usertimeline_write_user,25_redishashset_update_user,26_poststorage_storepost_uniqueid,27_usertimeline_write_uniqueid,28_redishashset_update_uniqueid,29_poststorage_storepost_mention,30_usertimeline_write_mention,31_redishashset_update_mention
0,zq33x3haw8xajnx3,968,2068,135,2574,667,2133,308,794,35001,...,616,1013,64,2521,369,37,1051,369,30,2648
1,0faxd7ka8l8pugjy,921,1008,191,748,1138,413,524,523,35530,...,2001,4302,34,2070,1288,36,3001,683,54,2579
2,6cuwt9yi6kqfcfru,105,930,168,1523,1001,1870,714,1454,20424,...,739,1433,36,516,986,49,3183,684,75,1082
3,v30o6hnyqdgv8adk,389,1008,301,1837,1254,1481,1346,1488,5355,...,3405,762,30,1576,617,58,2098,2123,46,1687
4,932sheoh8bzun62p,656,347,324,2687,688,2254,319,398,6048,...,2694,2698,45,2839,1345,77,1645,1160,64,1971

In [27]:
(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 790000 entries, 0 to 789999
Data columns (total 32 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   trace_id                           790000 non-null  str
 1   1_nginx_compose-post               790000 non-null  int64
 2   2_mediaservice_upload              790000 non-null  int64
 3   6_composepost_uploadmedia          790000 non-null  int64
 4   3_userservice_upload               790000 non-null  int64
 5   7_composepost_uploadcreator        790000 non-null  int64
 6   4_textservice_upload               790000 non-null  int64
 7   8_urlservice_upload                790000 non-null  int64
 8   9_usermentionservice_upload        790000 non-null  int64
 9   10_composepost_uploadtext          790000 non-null  int64
 10  12_composepost_uploadurl           790000 non-null  int64
 11  13_composepost_uploadusermention   790000 non-null  int64
 12  5_uniqueid_upload                  790000 non-null  int64
 13  11_composepost_uploaduniqueid      790000 non-null  int64
 14  14_poststorage_storepost_media     790000 non-null  int64
 15  15_usertimeline_write_media        790000 non-null  int64
 16  16_redishashset_update_media       790000 non-null  int64
 17  17_poststorage_storepost_text      790000 non-null  int64
 18  18_usertimeline_write_text         790000 non-null  int64
 19  19_redishashset_update_text        790000 non-null  int64
 20  20_poststorage_storepost_url       790000 non-null  int64
 21  21_usertimeline_write_url          790000 non-null  int64
 22  22_redishashset_update_url         790000 non-null  int64
 23  23_poststorage_storepost_user      790000 non-null  int64
 24  24_usertimeline_write_user         790000 non-null  int64
 25  25_redishashset_update_user        790000 non-null  int64
 26  26_poststorage_storepost_uniqueid  790000 non-null  int64
 27  27_usertimeline_write_uniqueid     790000 non-null  int64
 28  28_redishashset_update_uniqueid    790000 non-null  int64
 29  29_poststorage_storepost_mention   790000 non-null  int64
 30  30_usertimeline_write_mention      790000 non-null  int64
 31  31_redishashset_update_mention     790000 non-null  int64
dtypes: int64(31), str(1)
memory usage: 192.9 MB

In [20]:
df.shape

(790000, 32)

In [31]:
df.columns

Index(['trace_id', '1_nginx_compose-post', '2_mediaservice_upload',
       '6_composepost_uploadmedia', '3_userservice_upload',
       '7_composepost_uploadcreator', '4_textservice_upload',
       '8_urlservice_upload', '9_usermentionservice_upload',
       '10_composepost_uploadtext', '12_composepost_uploadurl',
       '13_composepost_uploadusermention', '5_uniqueid_upload',
       '11_composepost_uploaduniqueid', '14_poststorage_storepost_media',
       '15_usertimeline_write_media', '16_redishashset_update_media',
       '17_poststorage_storepost_text', '18_usertimeline_write_text',
       '19_redishashset_update_text', '20_poststorage_storepost_url',
       '21_usertimeline_write_url', '22_redishashset_update_url',
       '23_poststorage_storepost_user', '24_usertimeline_write_user',
       '25_redishashset_update_user', '26_poststorage_storepost_uniqueid',
       '27_usertimeline_write_uniqueid', '28_redishashset_update_uniqueid',
       '29_poststorage_storepost_mention', '30_usertimeline_write_mention',
       '31_redishashset_update_mention'],
      dtype='str')

In [32]:
df.describe()

,1_nginx_compose-post,2_mediaservice_upload,6_composepost_uploadmedia,3_userservice_upload,7_composepost_uploadcreator,4_textservice_upload,8_urlservice_upload,9_usermentionservice_upload,10_composepost_uploadtext,12_composepost_uploadurl,...,22_redishashset_update_url,23_poststorage_storepost_user,24_usertimeline_write_user,25_redishashset_update_user,26_poststorage_storepost_uniqueid,27_usertimeline_write_uniqueid,28_redishashset_update_uniqueid,29_poststorage_storepost_mention,30_usertimeline_write_mention,31_redishashset_update_mention
count,790000.000000,790000.000000,790000.000000,790000.000000,790000.000000,790000.000000,790000.000000,790000.000000,790000.000000,790000.000000,...,790000.000000,790000.000000,790000.000000,790000.000000,790000.000000,790000.000000,790000.000000,790000.000000,790000.000000,790000.000000
mean,555.961124,1010.693696,202.530615,2022.488670,809.225065,1517.667666,722.706557,820.611284,16873.490977,1115.900618,...,1923.537953,1720.739816,52.630044,2022.742991,1819.929665,43.633314,1924.076903,1772.092991,62.114280,1962.265465
std,262.717007,475.553734,94.063988,951.615895,382.037031,714.389779,310.884242,362.601494,10721.256437,519.175197,...,901.662329,806.283006,20.437946,952.077741,856.130173,14.740771,901.387688,831.033840,25.915331,922.100060
min,105.000000,201.000000,52.000000,410.000000,152.000000,301.000000,308.000000,311.000000,603.000000,270.000000,...,411.000000,369.000000,30.000000,411.000000,369.000000,30.000000,411.000000,369.000000,30.000000,411.000000
25%,364.000000,662.000000,132.000000,1324.000000,531.000000,993.000000,464.000000,529.000000,8820.000000,729.000000,...,1257.000000,1127.000000,33.000000,1324.000000,1192.000000,30.000000,1260.000000,1161.000000,39.000000,1283.000000
50%,550.000000,999.000000,199.000000,1999.000000,801.000000,1500.000000,700.000000,799.000000,14935.000000,1100.000000,...,1900.000000,1699.000000,50.000000,1999.000000,1799.000000,40.000000,1901.000000,1749.000000,60.000000,1938.000000
75%,736.000000,1336.000000,267.000000,2673.000000,1070.000000,2006.000000,935.000000,1069.000000,23268.000000,1471.000000,...,2540.000000,2272.000000,66.000000,2675.000000,2405.000000,53.000000,2542.000000,2340.000000,80.000000,2593.000000
max,2065.000000,3361.000000,684.000000,6378.000000,2722.000000,5055.000000,2480.000000,2608.000000,81004.000000,3762.000000,...,6343.000000,5871.000000,174.000000,6641.000000,6025.000000,135.000000,6177.000000,5837.000000,207.000000,6849.000000

In [33]:
df.dtypes

trace_id                               str
1_nginx_compose-post                 int64
2_mediaservice_upload                int64
6_composepost_uploadmedia            int64
3_userservice_upload                 int64
7_composepost_uploadcreator          int64
4_textservice_upload                 int64
8_urlservice_upload                  int64
9_usermentionservice_upload          int64
10_composepost_uploadtext            int64
12_composepost_uploadurl             int64
13_composepost_uploadusermention     int64
5_uniqueid_upload                    int64
11_composepost_uploaduniqueid        int64
14_poststorage_storepost_media       int64
15_usertimeline_write_media          int64
16_redishashset_update_media         int64
17_poststorage_storepost_text        int64
18_usertimeline_write_text           int64
19_redishashset_update_text          int64
20_poststorage_storepost_url         int64
21_usertimeline_write_url            int64
22_redishashset_update_url           int64
23_poststorage_storepost_user        int64
24_usertimeline_write_user           int64
25_redishashset_update_user          int64
26_poststorage_storepost_uniqueid    int64
27_usertimeline_write_uniqueid       int64
28_redishashset_update_uniqueid      int64
29_poststorage_storepost_mention     int64
30_usertimeline_write_mention        int64
31_redishashset_update_mention       int64
dtype: object

In [34]:
df.isnull().sum()

trace_id                             0
1_nginx_compose-post                 0
2_mediaservice_upload                0
6_composepost_uploadmedia            0
3_userservice_upload                 0
7_composepost_uploadcreator          0
4_textservice_upload                 0
8_urlservice_upload                  0
9_usermentionservice_upload          0
10_composepost_uploadtext            0
12_composepost_uploadurl             0
13_composepost_uploadusermention     0
5_uniqueid_upload                    0
11_composepost_uploaduniqueid        0
14_poststorage_storepost_media       0
15_usertimeline_write_media          0
16_redishashset_update_media         0
17_poststorage_storepost_text        0
18_usertimeline_write_text           0
19_redishashset_update_text          0
20_poststorage_storepost_url         0
21_usertimeline_write_url            0
22_redishashset_update_url           0
23_poststorage_storepost_user        0
24_usertimeline_write_user           0
25_redishashset_update_user          0
26_poststorage_storepost_uniqueid    0
27_usertimeline_write_uniqueid       0
28_redishashset_update_uniqueid      0
29_poststorage_storepost_mention     0
30_usertimeline_write_mention        0
31_redishashset_update_mention       0
dtype: int64

In [ ]:
df.head().T

,0,1,2,3
trace_id,zq33x3haw8xajnx3,0faxd7ka8l8pugjy,6cuwt9yi6kqfcfru,v30o6hnyqdgv8adk
1_nginx_compose-post,968,921,105,389
2_mediaservice_upload,2068,1008,930,1008
6_composepost_uploadmedia,135,191,168,301
3_userservice_upload,2574,748,1523,1837
7_composepost_uploadcreator,667,1138,1001,1254
4_textservice_upload,2133,413,1870,1481
8_urlservice_upload,308,524,714,1346
9_usermentionservice_upload,794,523,1454,1488
10_composepost_uploadtext,35001,35530,20424,5355
12_composepost_uploadurl,270,1404,578,1779
13_composepost_uploadusermention,836,2341,1756,878
5_uniqueid_upload,2368,1670,1994,3302
11_composepost_uploaduniqueid,397,518,1309,1051
14_poststorage_storepost_media,369,1459,2263,3334
15_usertimeline_write_media,59,56,30,65
16_redishashset_update_media,2009,1197,1766,2878
17_poststorage_storepost_text,1126,369,1988,1402
18_usertimeline_write_text,54,60,43,57
19_redishashset_update_text,2940,2728,1216,547
20_poststorage_storepost_url,1755,1809,1321,438
21_usertimeline_write_url,30,72,76,106
22_redishashset_update_url,616,2001,739,3405
23_poststorage_storepost_user,1013,4302,1433,762
24_usertimeline_write_user,64,34,36,30
25_redishashset_update_user,2521,2070,516,1576
26_poststorage_storepost_uniqueid,369,1288,986,617
27_usertimeline_write_uniqueid,37,36,49,58
28_redishashset_update_uniqueid,1051,3001,3183,2098
29_poststorage_storepost_mention,369,683,684,2123
30_usertimeline_write_mention,30,54,75,46
31_redishashset_update_mention,2648,2579,1082,1687